bangladict/urls.py
#
# Copyright 2010 BengDict Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf.urls.defaults import *

urlpatterns = patterns('bangladict.views',
    url(r'^$', 'dictionary_list', name='dict_list'),
    url(r'^search/$', 'word_search', name='dict_word_search'),
    url(r'^bulk/load/$', 'bulk_load', name='dict_bulk_load'),
    url(r'^accept_word/$', 'word_accept', name='dict_word_accept'),
    url(r'^(?P<dict_abbrev>\w+)/$', 'word_list', name='dict_word_list'),
    url(r'^(?P<dict_abbrev>\w+)/status/(?P<status>(new|rejected))/$', 'word_list',
        name='dict_word_list_status'),
    url(r'^comments/(?P<wid>\d+)/$', 'word_comments', name='dict_word_comments'),
    url(r'^(?P<dict_abbrev>\w+)/(?P<alpha>.{0,5})/$', 'word_list',
        name='dict_word_list_alpha'),
    url(r'^(?P<dict_abbrev>\w+)/edit/create/$', 'word_edit', name='dict_word_create'),
    url(r'^(?P<dict_abbrev>\w+)/edit/(?P<wid>\d+)/$', 'word_edit', name='dict_word_edit'),
    url(r'^word/(?P<dict_abbrev>\w+)/(?P<word>.+)/$', 'word_detail', name='dict_word_detail'),
)

urls.py
#
# Copyright 2010 BengDict Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

from bangladict.models import Dictionary

urlpatterns = patterns('',
    (r'^$', 'django.views.generic.simple.direct_to_template',
     {'template': 'index.html',
      'extra_context': {'dict': Dictionary.objects.all}}),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^accounts/', include('gaeauth.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^dictionary/', include('bangladict.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^contributor/', include('contributor.urls')),
)

bangladict/models.py
#
# Copyright 2010 BengDict Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.db import models
from django.contrib.auth.models import User

from django.utils.translation import ugettext_lazy as _


class Dictionary(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"))
    source_language = models.CharField(max_length=200,
                                       verbose_name=_("Source Language"))
    target_language = models.CharField(max_length=200,
                                      verbose_name=_("Target Language"))
    abbrev = models.CharField(max_length=10, verbose_name=_("Abbreviation"))
    pos = models.TextField(verbose_name=_('Parts of Speech'))
    alphabets = models.TextField(verbose_name=_('Alphabets'))

    class Meta:
        verbose_name = _('Dictionary')
        verbose_name_plural = _('Dictionaries')

    def __unicode__(self):
        return '%s (%s)' % (self.name, self.abbrev)

    @property
    def reverse_dict(self):
        d = self.abbrev.split('2')
        return "%s2%s" % (d[-1], d[0])

NEW, ACCEPTED, REJECTED, CLOSED = 0, 1, 2, 3
EDIT_STATES = [(NEW, _('New')), (ACCEPTED, _('Accepted')),
               (REJECTED, _('Rejected')), (CLOSED, _('Closed'))]

class Word(models.Model):
    dictionary = models.ForeignKey(Dictionary, verbose_name=_('Dictionary'))
    alpha = models.CharField(max_length=5, verbose_name=_('alpha'))
    original = models.CharField(max_length=50, verbose_name=_('Original'))
    translation = models.CharField(max_length=50,
                                   verbose_name=_('Translation'))
    phoneme = models.CharField(max_length=70, blank=True,
                               verbose_name=_('Phoneme'))
    pos = models.CharField(max_length=50, verbose_name=_('Parts of Speech'))
    description = models.TextField(blank=True, verbose_name=_('Description'))
    synonyms = models.CharField(max_length=500, blank=True,
                                verbose_name=_('Synonyms'))
    antonyms = models.CharField(max_length=500, blank=True,
                                verbose_name=_('Antonyms'))
    contributor = models.ForeignKey(User, verbose_name=_('Contributor'))
    status = models.IntegerField(default=NEW, choices=EDIT_STATES,
                                 verbose_name=_('Status'))
    added_at = models.DateTimeField(auto_now_add=True,
                                    verbose_name=_('Added at'))

    def __unicode__(self):
        return '%s -> %s' % (self.original, self.translation)

    def save(self, *args, **kwargs):
        self.alpha = self.original[0].lower()
        super(Word, self).save(*args, **kwargs)

class WordLoad(models.Model):
    contributor = models.ForeignKey(User, verbose_name=_('Contributor'))
    uploaded_at = models.DateTimeField(auto_now_add=True,
                                       verbose_name=_('Uploaded at'))
    hash = models.CharField(max_length=256, verbose_name=_('Hash'))
    file = models.TextField(verbose_name=_('File'))

    def __unicode__(self):
        return self.file[:20]

bangladict/forms.py
#
# Copyright 2010 BengDict Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django import forms

from .models import Word

class WordForm(forms.ModelForm):

    class Meta:
        model = Word
        exclude = ['dictionary', 'alpha', 'status', 'contributor',]

    def clean(self):
        for field in self.cleaned_data:
            if isinstance(self.cleaned_data[field], basestring):
                self.cleaned_data[field] = self.cleaned_data[field].strip()
        return self.cleaned_data

bangladict/views.py
#
# Copyright 2010 BengDict Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import hashlib
import logging

from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _
from django.views.generic.list_detail import object_list, object_detail
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse
from django.utils import simplejson as json
from django.db.utils import DatabaseError

from google.appengine.ext import deferred
from google.appengine.runtime import DeadlineExceededError

from .models import Word, Dictionary, WordLoad, NEW, ACCEPTED, REJECTED
from .forms import WordForm

def dictionary_list(request):
    return object_list(request, Dictionary.objects.all(),
                       template_object_name='dictionary', paginate_by=10)

def word_list(request, dict_abbrev, alpha=None, status='accepted'):
    status = {'new': NEW, 'accepted': ACCEPTED, 'rejected': REJECTED}[status]
    if status == NEW and not request.user.is_authenticated():
        raise Http404
    if status == REJECTED and not request.user.is_staff:
        raise Http404

    dictionary = get_object_or_404(Dictionary, abbrev=dict_abbrev)
    words = Word.objects.filter(dictionary=dictionary,
                                status=status).order_by('original')

    if alpha:
        words = words.filter(alpha=alpha)

    context = {
        'dictionary': dictionary,
        'alphabets': [a.strip() for a in dictionary.alphabets.split() if
                      a.strip()]
    }
    return object_list(request, words, template_object_name='word',
                       paginate_by=50, extra_context=context)

@login_required
def word_comments(request, wid):
    if not request.user.is_active:
        raise Http404

    word = get_object_or_404(Word, pk=wid)
    return render_to_response('bangladict/word_detail.html', {'word': word},
                              RequestContext(request))

def word_detail(request, dict_abbrev, word):
    dictionary = get_object_or_404(Dictionary, abbrev=dict_abbrev)
    words = Word.objects.filter(original=word, dictionary=dictionary)
    context = {'dictionary': dictionary}
    return object_list(request, words, template_object_name='word',
                       extra_context=context)

def word_search(request):
    abbrev = request.GET.get('dict', None)
    word = request.GET.get('word', None)
    if not all([abbrev, word]):
        raise Http404

    return HttpResponseRedirect(reverse('dict_word_detail', args=[abbrev,
                                                                  word]))

@csrf_protect
@login_required
def word_edit(request, dict_abbrev, wid=None):
    if not request.user.is_active:
        raise Http404

    dictionary = get_object_or_404(Dictionary, abbrev=dict_abbrev)
    if wid:
        word = get_object_or_404(Word, pk=wid)
        if not request.user.is_staff:
            if request.user != word.contributor:
                raise Http404('Not the contributor')
    else:
        word = None

    if request.method == 'POST':
        form = WordForm(data=request.POST, instance=word)
        if form.is_valid():
            entity = form.save(commit=False)
            entity.dictionary = dictionary
            entity.contributor = request.user
            entity.save()
            if not word:
                contrib = request.user.get_or_create_profile()
                contrib.number_words += 1
                contrib.save()
            return HttpResponseRedirect(reverse('dict_word_comments',
                                                args=[entity.pk]))
    else:
        form = WordForm(instance=word)

    context = {'form': form, 'dictionary': dictionary, 'word': word}

    return render_to_response('bangladict/word_edit.html', context,
                              RequestContext(request))

@login_required
def word_accept(request):
    if not request.user.is_staff:
        raise Http404

    accepted = set(request.POST.getlist('accept'))
    rejected = set(request.POST.getlist('reject'))
    common = accepted.intersection(rejected)
    accepted = accepted.difference(common)
    rejected = rejected.difference(common)

    for wid in accepted:
        word = get_object_or_404(Word, pk=wid)
        previous_status = word.status
        word.status = ACCEPTED
        word.save()

        profile = word.contributor.get_or_create_profile()
        profile.number_accepted += 1
        profile.save()

    for wid in rejected:
        word = get_object_or_404(Word, pk=wid)
        previous_status = word.status
        word.status = REJECTED
        word.save()

        profile = word.contributor.get_or_create_profile()
        if previous_status == ACCEPTED:
            profile.number_accepted -= 1
            profile.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@csrf_protect
@login_required
def bulk_load(request):
    if not request.user.is_active:
        raise Http404

    context = None
    if request.method == 'POST':
        f = request.FILES.get('file', None)
        if f:
            current = f.read()
            try:
                j = json.loads(current)
                hash = hashlib.sha1(current).hexdigest()

                if WordLoad.objects.filter(hash=hash).count() > 0:
                    msg = _('Already uploaded this file')
                else:
                    wfile = WordLoad(file=current, contributor=request.user,
                                     hash=hash)
                    wfile.save()
                    deferred.defer(add_words_from_file, wfile.pk)
                    msg = _('Thanks for the input. It will be added to the database soon')
            except Exception, e:
                logging.info(e)
                msg = _('Could not save this file.')
        else:
            msg = _('No file uploaded. Please select a file to upload')

        context = {'load_message': msg}

    return render_to_response('bangladict/bulk_load.html', context,
                              RequestContext(request))

def add_words_from_file(fid, index=0):
    logging.info("updating: %d %d" % (fid, index))
    wfile = WordLoad.objects.get(pk=fid)
    dicts = Dictionary.objects.all()
    dictionaries = {}
    for d in dicts:
        dictionaries[d.abbrev] = d

    profile = wfile.contributor.get_or_create_profile()

    try:
        word_file = json.loads(wfile.file)
        if index >= len(word_file):
            return

        counter = index
        for words in word_file[index:]:
            model = words.get('model', None)
            if not model or model != 'bangladict.word':
                continue
            fields = words.get('fields', None)
            if not fields:
                continue
            dictionary = dictionaries[fields['dictionary']]
            word = Word(dictionary=dictionary, contributor=wfile.contributor,
                        original=fields['original'],
                        translation=fields['translation'],
                        phoneme=fields['phoneme'], pos=fields['pos'],
                        synonyms=fields['synonyms'],
                        antonyms=fields['antonyms'],
                        description=fields['description'])
            word.save()
            counter += 1
    except DeadlineExceededError:
        logging.info('DeadlineExceededError')
        deferred.defer(add_words_from_file, fid, counter)
    except DatabaseError:
        logging.info('DatabaseError')
        deferred.defer(add_words_from_file, fid, counter+1)
    except Exception, e:
        logging.warning(e)
        logging.info('%s %d' % wfile.contributor.username, wfile.pk)

    profile.number_words += counter - index
    profile.save()

    logging.info(counter)

templates/bangladict/bulk_load.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Upload" %}{% endblock %}
{% block content %}
<h1>{% trans "Upload words" %}</h1>
<p>{% blocktrans %}Here you can load a file with word definitions. Currently json formatted
files are supported.{% endblocktrans %}</p>
<p>{{ load_message }}</p>
<form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
	<p>
	<label for="file">{% trans "File" %}:</label>
		<input type="file" name="file" value="" />
	</p>
	<input type="submit" name="submit" value="{% trans "Submit" %}" />
</form>
{% endblock %}

templates/bangladict/dictionary_list.html
{% extends "base.html" %}
{% load pagination_tags i18n %}
{% block title %}{% trans "Dictionaries" %}{% endblock %}
{% block content %}
<h1>{% trans "Dictionaries" %}</h1>
<ul>
	{% for dictionary in dictionary_list %}
	<li>
	<a href="{% url dict_word_list dictionary.abbrev %}">{{ dictionary.name }}</a>
	{% if user.is_authenticated %}
	<a href="{% url dict_word_list_status dictionary.abbrev,'new' %}">
		{% trans "New words" %}</a>
	{% endif %}
	{% if user.is_staff %}
	<a href="{% url dict_word_list_status dictionary.abbrev,'rejected' %}">
		{% trans "Rejected" %}</a>
	{% endif %}
	</li>
	{% endfor %}
</ul>
{% if is_paginated %}
{% paginate %}
{% endif %}
{% endblock %}

templates/bangladict/word_detail.html
{% extends "base.html" %}
{% load comments i18n %}
{% block title %}{% trans "Word" %}: {{ word.original }}{% endblock %}
{% block extra_head %}
<style>
	label, #id_name, #id_email, #id_url { display: none; }
</style>
{% endblock %}
{% block content %}
<h1>{% trans "Word" %}: {{ word.original }}</h1>
[{{ word.phoneme }}] ({{ word.pos }}) {{ word.translation }}
<p>{{ word.description }}</p>
<p><b>{% trans "Synonyms" %}:</b> {{ word.synonyms }}</p>
<p><b>{% trans "Antonyms" %}:</b> {{ word.antonys }}</p>
<p>{% trans "Added by" %} {{ word.contributor.display_name }}</p>
{% ifequal user word.contributor %}
<a href="{% url dict_word_edit word.dictionary.abbrev,word.pk %}">
	{%trans "Edit" %}</a>
{% endifequal %}
<h2>{% trans "Comments" %}</h2>
{% render_comment_list for word %}
<h2>{% trans "Post your comment" %}</h2>
{% if user.is_authenticated %}
{% render_comment_form for word %}
{% endif %}
{% endblock %}

templates/bangladict/word_edit.html
{% extends "base.html" %}
{% load dict_tags i18n %}
{% block title %}{{ dictionary.abbrev }}{% endblock %}
{% block content %}
<h1>{{ dictionary }}: <u>{% if word %}{% trans "Edit" %} {{ word }}{% else %}
		{% trans "Create new" %}{% endif %}</u></h1>
<form method="post" action="">{% csrf_token %}
	<table>
		{% for field in form %}
		<tr>
    {% if field.is_hidden %}
      <td>{{ field }}</td>
		{% else %}
		<th>{{ field.label_tag }} <br />
			{% if field.errors %}{{ field.errors }}{% endif %}
		</th>
		{% ifequal field.name "pos" %}
			<td><select name="pos" id="id_pos">
					<option value="">{% trans "Please select one" %}</option>
				{{ dictionary.pos|split_as_option:',' }}
			</select></td>
		{% else %}
		<td>{{ field }}</td>
		{% endifequal %}
    {% endif %}
	  </tr>
		{% endfor %}
	</table>
	<input type="submit" name="Submit" value="{% trans "Submit" %}" />
</form>
{% endblock %}

templates/bangladict/word_list.html
{% extends 'base.html' %}
{% load dict_tags pagination_tags i18n %}
{% block title %}{% trans "List" %}{% endblock %}
{% block content %}
<h1>
	<a href="{% url dict_word_list dictionary.abbrev %}">{{ dictionary.name }}</a>
</h1>
<ul class="alpha-list">
	{% for alpha in alphabets %}
	<li><a href="{% url dict_word_list_alpha dictionary.abbrev,alpha %}">{{ alpha }}</a></li>
	{% endfor %}
</ul>
<p><a href="{% url dict_word_create dictionary.abbrev %}">
	{% trans "Add a new word" %}</a></p>
{% regroup word_list by original as words %}
{% if user.is_staff %}
<form action="{% url dict_word_accept %}" method="POST">{% csrf_token %}
{% endif %}
<dl class="word-list">
	{% for word in words %}
	<dt><a href="{% url dict_word_detail dictionary.abbrev,word.grouper %}">{{ word.grouper }}</a></dt>
	<dd><ul>
		{% for item in word.list %}
		<li>
		{% ifchanged %}[{{ item.phoneme }}]{% endifchanged %} ({{ item.pos }})
		{% for translation in item.translation|split:';' %}
		<a href="{% url dict_word_detail dictionary.reverse_dict,translation %}">
			{{ translation }}{% if not forloop.last %},{% endif %}
		</a>
		{% endfor %}
		<p>{{ item.description }}</p>
		{% if item.synonyms %}
		<p><b>{% trans "Synonyms" %}:</b> {% for synonym in item.synonyms|split:';' %}
		<a href="{% url dict_word_detail dictionary.abbrev,synonym %}">
			{{ synonym }}</a>{% if not forloop.last %},{% endif %}
			{% endfor %}</p>
		{% endif %}
		{% if item.antonyms %}
		<p><b>{% trans "Antonyms" %}:</b> {% for antonym in item.antonyms|split:';' %}
		<a href="{% url dict_word_detail dictionary.abbrev,antonym %}">
			{{ antonym }}</a>{% if not forloop.last %},{% endif %}
			{% endfor %}</p>
		{% endif %}
		{% ifnotequal item.status 1 %}
		<p><a href="{% url dict_word_comments item.pk %}">{% trans "Comments" %}</a>
		{% ifequal user item.contributor %}
		<a href="{% url dict_word_edit item.dictionary.abbrev,item.pk %}">
			{% trans "Edit" %}</a>
		{% endifequal %}</p>
		{% if user.is_staff %}
		<label for="accept{{ item.pk }}">
		<input type="checkbox" name="accept" id="accept{{ item.pk }}"
		value="{{ item.pk }}" /> {% trans "Accept" %}</label>
		<label for="reject{{ item.pk }}">
		<input type="checkbox" name="reject" id="reject{{ item.pk }}"
		value="{{ item.pk }}" /> {% trans "Reject" %}</label>
		{% endif %}
		{% endifnotequal %}
		</li>
		{% endfor %}
	</ul></dd>
	{% empty %}
	{% trans "No word found!" %}
	{% endfor %}
</dl>
{% if user.is_staff %}
<input type="submit" value="{% trans "Save" %}"/>
</form>
{% endif %}
{% if is_paginated %}
{% paginate %}
{% endif %}
{% endblock %}